### ISSUE TITLE
[RFC] Pagination vs infinite loading

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-vault#213]
I don't have to tell you that currently all lists are done using infinite loading. There are two downsides to this:
- Progress is lost when moving to another page and back
- Performance gets worse the longer you scroll

The alternative would be the old school pagination (think Google search results).
It fixes both problems of infinite loading.
The only problem it could cause that I can think of is selecting multiple items across multiple pages.

Which one would you prefer in the future?

**Comment by echo6ix** [comment]
I'm indifferent, but would lean towards pagination for better performance.

Perhaps it can be a mix of both. On pages where people tend to have a massive amont of items, such as scenes and images, use pagination. And infinite scrolling for studios, movies, actors, and labels. I guess my opinion depends on how many items tend to cause performance degradation, and how many items each of those pages tends to have. Do people tend to have more than 300 actors or studios?

My only preference for "infinite scrolling" would be for: (1) full screen image viewer [if it's even applicable to that application], and (2) a data table bulk-edit mode for each of scenes, for actors, for studios, etc.

In fact I think when and if a data table bulk-edit is implemented it should be the primary method of selecting multiple items for any kind of editing. The thumbnail modes are not efficient for that type of task, and I think you've already highlighted one reason why.

**Comment by tltgt** [comment]
How about "pagination" like this https://community.home-assistant.io/t/deconz-official-thread/100504

Check out the scroll bar on the right of the page.

**Comment by boi123212321** [comment]
@tltgt That looks like infinite scroll to me

**Comment by tltgt** [comment]
Did you notice the scroll bar on the right side? That can be used to jump throughout the entire range of posts quickly and quite accurately.

**Comment by GernBlanston12** [comment]
Can't you just do pagination, but with buffers so it looks like/acts like infinite scrolling with limited impact to performance? Have it load to two pages ahead/behind current, then stop until user scrolls top/down 1 page. Then, grab another page buffer's worthy from that position?

**Comment by tritnaha** [comment]
I'd prefer pagination personally, being able to go back to where i was before when browsing a huge collection is a must have!

**Comment by yoshnopa** [comment]
I prefer infinite scroll for its modern look&feel, but I can see the point of not getting back to the position you were when you click away. However, this is solvable, as reddit and twitter demonstrate

I've got a quick code here which is working on firefox and chrome via console really good, only thing missing is the page your currently on, which means that when you scroll down now, it catches elements already loaded because it doesnt know what is already there. If @boi123212321 explains me how the infinite scroll is implemented this can be quickly transferred.
A quick intro on how this is done, basically you are carrying the (html) data around in a cookie, which is created when you click on an item, but deleted when you are not returning to the same page, but rather a different one. This means a bit more data upload, however when the connection is good enough for streaming videos, there should be no problem. 

Add to the click event of items:
`localStorage.setItem("url", window.location.href);
localStorage.setItem("backcache", document.getElementsByClassName("row")[0].innerHTML);
localStorage.setItem("scrollposition", document.documentElement.scrollTop);`
+ setting the pagenumber the same way (the variable used for the scrolling function to find the next data

Add after loading page of scenes, movies etc (best case before loading elements):
`if (localStorage.getItem("url") === window.location.href){
	document.getElementsByClassName("row")[0].innerHTML=localStorage.getItem("backcache");
	document.documentElement.scrollTop = localStorage.getItem("scrollposition");
}
localStorage.removeItem("backcache");
localStorage.removeItem("scrollposition");
localStorage.removeItem("url");`
again + getting the page number and setting it to the local variable, as well as deleting it from the localStorage.

**Comment by boi123212321** [comment]
@yoshnopa Theoretically yes; practically, you would need to store the progress (items) plus the pagination info in Vuex (there's are already dedicated store modules for the different pages in /app/src/store) every time something is loaded, then retrieve it when the page is mounted again later. Just storing and loading HTML isn't gonna cut it in Vue. Also, using Vuex would help with space limits, as it is stored in the JS heap, not local storage - which could still be done separately to store between-sessions progress (essentially a JSON stringified snapshot of the Vuex content), but I don't think that's too important.

**Comment by yoshnopa** [comment]
Ok, I don't know vuex yet, but after looking at the code am I correct to assume that its basically caching current values of the page for quicker loading and sending changes to the server if necessary? 
And therefore, one would implement another file there, reacting to mutations to the according values, but without sending this information to the server, but using it when your loading the view? 
So maybe save the html in vuex together with the progress and pagination info, so nothing has to be reloaded while still having everything in a vue style code base?

**Comment by boi123212321** [comment]
@yoshnopa You can't cache HTML, it goes against the way Vue works. For instance, all event handlers would just be gone + all reactivity.

Vuex is a way to manage global state. It does not necessarily connect to the server, except for when you want to. Right now, all loaded scenes are stored in the page data (views/Scenes.vue). All page data is destroyed when you move to another, so this would have to be moved into the Vuex store, which persists as long as the page is open.

**Comment by natcoso9955** [comment]
So my preference would be that you can set each page preference in the config, and/or a site-wide setting.

I find that the images section is way to hard to navigate when you have 8000+ images with infinite scroll.

Unless we could have the best of both worlds solution. Ozbargain uses infinite scroll, but in the URL it appends ?page=X as you scroll through blocks. If we could have infinite scroll but with floating page navigation, maybe that's a compromise?
