### ISSUE TITLE
[Repo] (Auto) Lint & formatting

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-vault#608]
@leadwolf 
https://github.com/marketplace/actions/lint-action something like that?

**Comment by leadwolf** [comment]
Yeah. I didn't even think of that, just of using ESLint & Prettier while coding. But that action will help enforce the configs we set in place.
I guess the question now, is what eslint configs/rules do we want.
We should of course extend [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) and then I think most people would be fine with adding [StandardJS](https://github.com/standard/eslint-config-standard) or [AirBnB](https://github.com/iamturns/eslint-config-airbnb-typescript) and then maybe some custom rules.

For example, StandardJS does not enforce semi-colons. It also does not allow dangling commas, but I personally find them useful because they simplify git diffs

I also like [eslint-plugin-promise](https://github.com/xjamundx/eslint-plugin-promise) . For example it helps catch common errors like forgetting a `.catch` and has a rule that promotes async/await instead of chaining

Then for the vue folder, I've found [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) has been sufficient for me.

I also just found [dustinspecker/awesome-eslint](https://github.com/dustinspecker/awesome-eslint) that can help us get ideas
